services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EnterpriseToolingForSymfony\WebuiBundle\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection"
            - "../src/Entity"
            - "../src/Dto"
            - "../src/ApiDto"
            - "../src/Enum"
            - "../src/Resources"
            - "../tests"
